# Documentation:
# https://starship.rs/config/
# https://starship.rs/advanced-config/#style-strings

# Color scheme:
# https://github.com/dracula/dracula-theme

# Don't print a new line at the start of the prompt
add_newline = false
# use_symbol_for_status = true

[username]
show_always = true
style_user="bold #ff79c6"
format = "[$user]($style)ğŸ”¥ğŸ’€ğŸ”¥"

[hostname]
ssh_only = false
style="bold #8be9fd"
format = "[$hostname]($style) "

[character]
success_symbol = '[\(à¹‘Ë˜ï¸¶Ë˜à¹‘\)ãƒãªã«!?](bold #f8f8f2)'
error_symbol = '[\(ãƒà² ç›Šà² \)ãƒãªã«!?](bold #ff5555)'
vicmd_symbol = '[\(à¹‘Ë˜ï¸¶Ë˜à¹‘\)ãƒãªã«!?](bold #6272a4)'

[directory]
style = "bold #bd93f9"
truncation_length = 5
truncate_to_repo = false

[git_branch]
style = "bold #50fa7b"
symbol = "ğŸŒ± "

[git_status]
style = "bold #ff5555"

[time]
disabled = false
format = '[\[ $time \]](bold #ffb86c) '
